spring.application.name=book-a-hike-service
spring.security.user.name=nico123
spring.security.user.password=123456

spring.datasource.url=jdbc:postgresql://book-a-hike071425-johnicoirinco-4bf7.e.aivencloud.com:12793/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_f_KMNQib4DdwLvJGnlq

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.driver-class-name=org.postgresql.Driver

# security
jwt.secret=35fc33600ba2cf18f88f2f2b5e727a5fdf15526d669eb37b66a88b641eee84fe

# Optional for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.jdbc=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.hibernate.SQL=DEBUG
